// laravel10_inertia_vue/resources/js/Pages/Post/Create.vue
<script setup>

import { useForm, Link } from '@inertiajs/vue3';
const form = useForm({
    title: "",
    body: ""
});

const submit = () => {
    form.post("/posts");
}

</script>


<template>
    <div class="container">
        <h1 class="display-1">Welcome to Vue with laravel</h1>
        <Link class="btn btn-warning " :href="route('posts.index')">
            Post List</Link>

        <form @submit.prevent="submit" class="form">
            <div class="mb-4">
                <label for="title" class="block text-gray-700 text-sm font-bold mb-2">
                    Title:</label>
                <input type="text"
                    class="form-control"
                    placeholder="Enter Title" id="title" v-model="form.title" />

            </div>

            <div class="mb-4">
                <label for="body" class="block text-gray-700 text-sm font-bold mb-2">
                    Body:</label>
                <textarea
                    class="form-control"
                    id="body" v-model="form.body" placeholder="Enter Body"></textarea>
            </div>

            <button type="submit"
                class="btn btn-success">
                Submit
            </button>

        </form>
    </div>
</template>


<style scoped></style>

// laravel_react_breeze/resources/js/Pages/Posts/Create.jsx
import { useForm } from "@inertiajs/react";
import React from "react";


export default function Create() {
    const { data, setData,errors, post} = useForm({
        title: "",
        body: ""
    })

    console.log(data)

    function handleSubmit(e){
        e.preventDefault();
        post(route("post.store"));
        // alert('Data Sent')
    }
    return (
        <>
            <div>
                <h1>Post Entry</h1>
                <form  onSubmit={handleSubmit}>
                    <fieldset>
                    Title: <br /><input type="text" name="title" placeholder="Enter Title" value={data.title} onChange={(e)=> setData('title', e.target.value)} /> <span>{errors.title}</span><br />
                    Body: <br />
                    <textarea
                        name="body"
                        id=""
                        placeholder="Enter Body" onChange={(e)=> setData('body', e.target.value)}
                    >{data.body}</textarea> <span>{errors.body}</span><br />
                    <button type="submit" name="submit">SUBMIT</button>
                    </fieldset>
                </form>
            </div>
        </>
    );
}
